# Generated by Django 2.1.5 on 2019-02-09 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190209_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='picture',
        ),
    ]
