# Generated by Django 2.1.5 on 2019-02-09 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_remove_goods_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='picture',
            field=models.FileField(default=2, upload_to='./upload/'),
            preserve_default=False,
        ),
    ]
